In [1]:
import pandas as pd

monthly_sales = pd.read_csv("../data/cleaned/monthly_sales.csv")
yearly_sales = pd.read_csv("../data/cleaned/yearly_sales.csv")
category_sales = pd.read_csv("../data/cleaned/category_sales.csv")

print("Sales data loaded successfully!")

Sales data loaded successfully!

In [2]:
best_month = monthly_sales.loc[
    monthly_sales["sales"].idxmax()
]

best_month

order_month       2017-11
sales          1010271.37
Name: 13, dtype: object

In [3]:
worst_month = monthly_sales.loc[
    monthly_sales["sales"].idxmin()
]

worst_month

order_month    2016-12
sales             10.9
Name: 2, dtype: object

In [4]:
sales_2017 = yearly_sales.loc[
    yearly_sales["year"] == 2017, "sales"
].iloc[0]

sales_2018 = yearly_sales.loc[
    yearly_sales["year"] == 2018, "sales"
].iloc[0]

growth_2018 = ((sales_2018 - sales_2017) / sales_2017) * 100

print("Sales Growth from 2017 to 2018:", round(growth_2018, 2), "%")

Sales Growth from 2017 to 2018: 19.99 %

In [5]:
best_category = category_sales.loc[
    category_sales["sales"].idxmax()
]

best_category

category    beleza_saude
sales         1258681.34
Name: 0, dtype: object

In [6]:
product_sales = pd.read_csv("../data/cleaned/product_sales.csv")

best_product = product_sales.loc[
    product_sales["sales"].idxmax()
]

best_product

product_id    bb50f2e236e5eea0100680137654686c
sales                                  63885.0
Name: 0, dtype: object

In [7]:
payment_summary = pd.read_csv("../data/cleaned/payment_summary.csv")

best_payment = payment_summary.loc[
    payment_summary["order_count"].idxmax()
]

best_payment

KeyError: 'order_count'

In [8]:
payment_summary.columns

Index(['payment_type', 'payment_count'], dtype='object')

In [9]:
best_payment = payment_summary.loc[
    payment_summary["payment_count"].idxmax()
]

best_payment

payment_type     credit_card
payment_count          76795
Name: 0, dtype: object

In [10]:
top_city = pd.read_csv("../data/cleaned/top_customer_cities.csv")

top_city.head(1)

        city  customer_count
0  sao paulo           15540

In [11]:
top_state = pd.read_csv("../data/cleaned/top_customer_states.csv")

top_state.head(1)

  state  customer_count
0    SP           41746

In [12]:
review_kpi = pd.read_csv("../data/cleaned/review_kpi.csv")

review_kpi

                 metric  value
0  average_review_score   4.09

In [13]:
delivery_kpi = pd.read_csv("../data/cleaned/delivery_kpi.csv")

delivery_kpi

                  metric  value
0  average_delivery_days  12.09
1  on_time_delivery_rate  89.15

In [14]:
order_status = pd.read_csv("../data/cleaned/order_status_summary.csv")

order_status

  order_status  order_count
0    delivered        96478
1      shipped         1107
2     canceled          625
3  unavailable          609
4     invoiced          314
5   processing          301
6      created            5
7     approved            2

In [15]:
delivered_orders = order_status.loc[
    order_status["order_status"] == "delivered",
    "order_count"
].iloc[0]

total_status_orders = order_status["order_count"].sum()

delivered_rate = (delivered_orders / total_status_orders) * 100

print("Delivered Order Rate:", round(delivered_rate, 2), "%")

Delivered Order Rate: 97.02 %

In [16]:
print("BUSINESS INSIGHTS")
print("------------------")
print("Best Month:", best_month["order_month"], "-", best_month["sales"])
print("Sales Growth (2017 to 2018):", round(growth_2018, 2), "%")
print("Top Category:", best_category["category"], "-", best_category["sales"])
print("Top Product:", best_product["product_id"], "-", best_product["sales"])
print("Most Used Payment:", best_payment["payment_type"], "-", best_payment["payment_count"])
print("Top Customer City:", top_city.iloc[0]["city"], "-", top_city.iloc[0]["customer_count"])
print("Top Customer State:", top_state.iloc[0]["state"], "-", top_state.iloc[0]["customer_count"])
print("Average Review Score:", review_kpi.iloc[0]["value"], "/ 5")
print("Average Delivery Time:", delivery_kpi.iloc[0]["value"], "days")
print("On-Time Delivery Rate:", delivery_kpi.iloc[1]["value"], "%")
print("Delivered Order Rate:", round(delivered_rate, 2), "%")

BUSINESS INSIGHTS
------------------
Best Month: 2017-11 - 1010271.37
Sales Growth (2017 to 2018): 19.99 %
Top Category: beleza_saude - 1258681.34
Top Product: bb50f2e236e5eea0100680137654686c - 63885.0
Most Used Payment: credit_card - 76795
Top Customer City: sao paulo - 15540
Top Customer State: SP - 41746
Average Review Score: 4.09 / 5
Average Delivery Time: 12.09 days
On-Time Delivery Rate: 89.15 %
Delivered Order Rate: 97.02 %